### ISSUE TITLE
HB_LEAN breaks camera on msm8998

### ISSUE THREAD

**Issue by tts2k** [crdroidandroid/android_external_harfbuzz_ng#1]
Apologize if this isn't an issue, I'm new to this.
So I'm building [Floko Rom](https://floko.maud.io/) for chiron, and I noticed that the camera wasn't working. After checking logcat, I found this part which I deemed to be relevent:
```
03-19 08:28:47.120 10858 10858 E HAL     : load: module=/vendor/lib/hw/camera.msm8998.so
03-19 08:28:47.120 10858 10858 E HAL     : dlopen failed: cannot locate symbol "hb_unicode_funcs_set_decompose_compatibility_func" referenced by "/vendor/lib/libminikin-v28.so"...
03-19 08:28:47.120 10858 10858 E CamPrvdr@2.4-legacy: Could not load camera HAL module: -22 (Invalid argument)
```
It seems like `hb_unicode_funcs_set_decompose_compatibility_func` is [on the list of HarfBuzz's deprecated api](https://harfbuzz.github.io/harfbuzz-hb-deprecated.html), but is being used by libminikin
Tracing down Floko manifest, I saw that they are [syncing HarfBuzz from crdroid](https://github.com/FlokoROM/manifesto/blob/b9b3e03d1a280fdc61b7bbaf9e53aca8deecd277/snippets/crdroid.xml#L32), and recently you enabled `HB_LEAN` which will remove deprecated functions.
I think that adding `HB_LEAN` might have broken camera on msm8998. After rebuilding the rom with https://github.com/crdroidandroid/android_external_harfbuzz_ng/commit/3d1cff0fa4bfcc2177da39ac515819477ce0a28c reverted, the camera is working again.
From what I have heard, official crDroid 7.3, 7.4 on chiron is also experiencing an issue with camera and I think this might be the cause.

**Comment by neobuddy89** [comment]
@xNombre please check and revert if necessary.

**Comment by jomadeto** [comment]
Can confirm problem with camera on chiron after 7.3 update, same error on log. Reverted locally the commit and camera working again.

**Comment by xNombre** [comment]
Hello guys! Thanks for this robust description. This change was tested on really old camera HAL and I thought we wont loose any needed dependencies, apparently its not a case for some fantastic OEM ideas (:

I will discuss this change on our devs chat. For now the most effective way for me is to undef HB_DISABLE_DEPRECATED. Could you confirm it fixes your problem?

**Comment by xNombre** [comment]
To elaborate: Just remove "#define HB_DISABLE_DEPRECATED" from file src/hb-config.hh

**Comment by jomadeto** [comment]
It's late here, tomorrow check it

**Comment by tts2k** [comment]
Can confirm that removing `HB_DISABLE_DEPRECATED` from `HB_LEAN`  ifdef block fixed the camera issue

**Comment by jomadeto** [comment]
Yes, confirmed that removing "#define HB_DISABLE_DEPRECATED" from file src/hb-config.hh fix the problem. Thanks

**Comment by xNombre** [comment]
Thanks for report guys, I will push a fix soon :)
